impr:documentation and workflow
* impr:reduce calculations when calculated information is known prior to ctor call
* impr:workflow names
* fix:static analysis problems
* chg:disable PHPCodeStyle as it doesn't support property hooks well yet

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,105 +10,69 @@ on:
 jobs:
   analysis:
     runs-on: ubuntu-latest
-
-    # If you want analysis to wait for tests to complete, add needs:
-    needs: build-test
-
+    needs: tests
     steps:
       - name: Check out repository
         uses: actions/checkout@v3
 
-      - name: Set up PHP 8.4
+      - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with:
           php-version: '8.4'
 
-      - name: Install Composer dependencies
-        uses: php-actions/composer@v7
+      - name: Composer install
+        uses: ramsey/composer-install@v2
+
+      - name: Run PHPStan
+        if: success() || failure()
+        run: composer exec -- phpstan analyse --memory-limit=512M --ansi --no-progress --level=max src tests --error-format=checkstyle > phpstan-checkstyle.xml
+
+      - name: Report PHPStan
+        if: success() || failure()
+        uses: jwgmeligmeyling/checkstyle-github-action@master
         with:
-          command: install --no-interaction --prefer-dist
+          name: PHPStan report
+          path: phpstan-checkstyle.xml
 
-      - name: Run phpstan
-        run: vendor/bin/phpstan analyse --level=max src tests --error-format=junit > phpstan-junit.xml
+#      - name: Run PHPCodeSniffer
+#        if: success() || failure()
+#        run: composer exec -- phpcs --colors --report=checkstyle --report-checkstyle=phpcs-checkstyle.xml
+#
+#      - uses: jwgmeligmeyling/checkstyle-github-action@master
+#        if: success() || failure()
+#        with:
+#          name: PHPCodeSniffer report
+#          path: phpcs-checkstyle.xml
 
-      - name: Upload phpstan results
-        uses: actions/upload-artifact@v3
-        with:
-          name: phpstan-junit
-          path: phpstan-junit.xml
-
-      - name: Report phpstan results
-        uses: dorny/test-reporter@v1
-        if: always()
-        with:
-          name: "PHPStan Analysis"
-          path: "phpstan-junit.xml"
-          reporter: "junit"
-          fail-on-error: false
-
-      - name: Run phpcs
-        run: vendor/bin/phpcs --standard=PSR12 --report=junit --report-file=phpcs-junit.xml src tests
-
-      - name: Upload phpcs results
-        uses: actions/upload-artifact@v3
-        with:
-          name: phpcs-junit
-          path: phpcs-junit.xml
-
-      - name: Report phpcs results
-        uses: dorny/test-reporter@v1
-        if: always()
-        with:
-          name: "PHPCS Analysis"
-          path: "phpcs-junit.xml"
-          reporter: "junit"
-          fail-on-error: false
-
-  build-test:
+  tests:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        php-version: [ 8.2, 8.3, 8.4 ]
+        php: [ "8.4" ]
+        dependency-versions: [ lowest, highest ]
 
     steps:
       - name: Check out repository
         uses: actions/checkout@v3
 
-      - name: Set up PHP ${{ matrix.php-version }}
+      - name: Set up PHP ${{ matrix.php }}
         uses: shivammathur/setup-php@v2
         with:
-          php-version: ${{ matrix.php-version }}
+          php-version: ${{ matrix.php }}
 
-      - name: Install Composer dependencies
-        uses: php-actions/composer@v7
-        with:
-          command: install --no-interaction --prefer-dist
+      - name: Composer install
+        uses: ramsey/composer-install@v2
 
       - name: Generate tz data
         run: make tz
 
       - name: Run PHPUnit
-        uses: php-actions/phpunit@v2
-        with:
-          args: "--coverage-clover coverage.xml --log-junit junit.xml --coverage-text"
+        if: success() || failure()
+        run: composer exec -- phpunit --colors=always --log-junit=phpunit-${{ matrix.php }}-${{ matrix.dependency-versions }}.xml
 
-      - name: Upload coverage artifact
-        uses: actions/upload-artifact@v3
+      - name: Publish Test Results
+        uses: EnricoMi/publish-unit-test-result-action@v2
+        if: success() || failure()
         with:
-          name: coverage
-          path: coverage.xml
-
-      - name: Upload test results artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: junit
-          path: junit.xml
-
-      - name: Report test results
-        uses: dorny/test-reporter@v1
-        if: always()
-        with:
-          name: 'PHPUnit Tests'
-          path: 'junit.xml'
-          reporter: 'junit'
-          fail-on-error: false
+          check_name: "PHPUnit report (${{ matrix.php }} ${{ matrix.dependency-versions }} deps)"
+          junit_files: "phpunit-*.xml"
